### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by viktorpi** [yuliapi/carousel-carousel#1]
Component works perfectly fine if you use webpack and import JS and CSS files there. 
In case add link to JS file directly into HTML page we get an issue in Chrome referencing to carousel-carousel.js file.:

`Uncaught ReferenceError: exports is not defined`

**Comment by yuliapi** [comment]
Issue fixed by customizing Babel options:
` "presets": [
      ["env", {
        loose: true,
        modules: false}]
      ],
      "plugins": ["transform-es2015-modules-strip"]`
